import React from "react";
import { Dumbbell, Target } from "lucide-react";

import type { GuideSection } from "@/components/mensHealthGuide/types";

export const hangersGuide: GuideSection = {
  title: "Penis Hangers & Extenders",
  icon: <Dumbbell className="h-5 w-5" />,
  whatIsIt:
    "Penis hangers attach weight to the penis to provide sustained stretching tension. Extenders are medical-grade traction devices that hold the penis in an extended state for hours. Both work on the principle that sustained tension can encourage cellular growth (traction-induced tissue growth). Extenders have some clinical studies supporting their use.",
  howToUse: [
    "HANGERS: Attach hanger to shaft below glans, start with 1-2 lbs",
    "HANGERS: Hang for sets of 10-20 minutes with breaks",
    "HANGERS: Gradually increase weight over weeks/months",
    "EXTENDERS: Follow device instructions for attachment",
    "EXTENDERS: Wear for 4-8 hours daily (can be split into sessions)",
    "EXTENDERS: Start with lower tension and shorter duration",
    "Both: Always warm up before use",
    "Both: Check circulation every 10-15 minutes",
  ],
  benefits: [
    "Extenders have clinical studies showing potential efficacy",
    "Sustained tension vs. manual exercises",
    "Hands-free (extenders can be worn under clothes)",
    "May help with Peyronie's curvature (extenders)",
    "Measurable, consistent tension application",
    "Can target length specifically",
  ],
  cons: [
    "Expensive equipment investment",
    "Requires significant time commitment (hours daily)",
    "Can be uncomfortable especially initially",
    "Learning curve for proper attachment",
    "Visible under tight clothing (extenders)",
    "Hangers have higher injury risk than extenders",
  ],
  warnings: [
    "Never hang weights while sleeping",
    "Check for circulation every 10-15 minutes",
    "Do not exceed recommended weights for your experience level",
    "Remove immediately if you experience numbness or cold",
    "Not recommended for those with blood clotting disorders",
    "Extenders: Follow break schedule strictly",
  ],
  dangers: [
    "Excessive weight can cause nerve damage",
    "Poor attachment can restrict blood flow",
    "Can cause blisters and skin damage",
    "Risk of dropping weights and causing injury",
    "Prolonged use without breaks can cause tissue damage",
    "Improperly fitting extenders can cause pressure sores",
  ],
  safetyTips: [
    "Start very light - 1-2 lbs for hangers",
    "Use proper attachment methods to distribute pressure",
    "Take breaks every 20 minutes for hangers",
    "Never sleep while wearing any device",
    "Keep the area dry to prevent skin issues",
    "Listen to your body - discomfort is okay, pain is not",
    "Buy quality devices from reputable manufacturers",
  ],
  whatToLookFor: [
    "Discoloration of glans (remove immediately if purple/blue)",
    "Cold glans or shaft (circulation issue)",
    "Numbness or tingling",
    "Blisters or skin breakdown",
    "Excessive swelling",
    "Any sharp or intense pain",
  ],
  experienceLevel: ["intermediate", "advanced"],
};

export const penisExtenderGuide: GuideSection = {
  title: "Penis Extenders (ADS/Traction Devices)",
  icon: <Dumbbell className="h-5 w-5" />,
  whatIsIt:
    "Penis extenders are medical-grade traction devices that apply gentle, constant stretch to the penis. ADS (All Day Stretcher) versions can be worn discreetly under clothing for extended periods. They work on the principle of tissue expansion through sustained tension, similar to orthopedic limb lengthening.",
  howToUse: [
    "Read all manufacturer instructions carefully before first use",
    "Start with low tension settings and short duration (2-4 hours)",
    "Attach device according to specific model instructions",
    "Check comfort and circulation every 30-60 minutes",
    "Gradually increase wear time over weeks (up to 6-8 hours)",
    "Take breaks to maintain circulation",
    "Use padding/sleeves to prevent skin irritation",
    "Clean device regularly to prevent infection",
  ],
  benefits: [
    "Clinical studies show potential for length gains",
    "FDA-cleared devices available",
    "Can be worn discreetly during daily activities",
    "Consistent, measurable tension application",
    "May help correct Peyronie's curvature",
    "Hands-free operation allows multitasking",
    "More controlled than manual methods",
  ],
  cons: [
    "Expensive initial investment ($100-$400+)",
    "Requires significant daily time commitment",
    "Can be uncomfortable initially",
    "Visible under tight clothing",
    "Learning curve for proper attachment",
    "May slip or need adjustment",
    "Results require months of consistent use",
  ],
  warnings: [
    "Never sleep while wearing any extender",
    "Remove immediately if you feel numbness or tingling",
    "Do not exceed recommended tension levels",
    "Check circulation regularly - glans should remain healthy color",
    "Not recommended for those with blood clotting disorders",
    "Consult doctor if you have Peyronie's disease first",
  ],
  dangers: [
    "Excessive tension can cause nerve damage",
    "Poor attachment can restrict blood flow",
    "Can cause skin abrasion or blisters",
    "Improper use may worsen existing conditions",
    "Long sessions without breaks can cause tissue damage",
  ],
  safetyTips: [
    "Purchase from reputable medical device manufacturers",
    "Start with the absolute minimum tension",
    "Use timer reminders to check device",
    "Keep skin dry to prevent irritation",
    "Rotate attachment points to avoid pressure sores",
    "Allow recovery days if any soreness develops",
    "Document your routine and any issues",
  ],
  whatToLookFor: [
    "Glans turning purple or blue (remove immediately)",
    "Cold sensation in penis (circulation issue)",
    "Skin irritation or abrasion",
    "Numbness that persists after removal",
    "Any cuts or wounds from device",
    "Decreased sensitivity after use",
  ],
  experienceLevel: ["intermediate", "advanced"],
  visualSteps: [
    { step: 1, title: "Preparation", description: "Clean device and prepare attachment mechanism" },
    { step: 2, title: "Positioning", description: "Ensure flaccid state, apply protective padding" },
    { step: 3, title: "Attachment", description: "Secure glans according to device instructions", caution: "Do not overtighten" },
    { step: 4, title: "Set Tension", description: "Start at lowest comfortable tension setting" },
    { step: 5, title: "Monitor", description: "Check every 30-60 minutes during wear" },
  ],
};

export const clampingGuide: GuideSection = {
  title: "Clamping",
  icon: <Target className="h-5 w-5" />,
  whatIsIt:
    "Clamping involves using a device (cable clamp, constriction ring, or specialized clamp) to restrict blood outflow from an erect penis, trapping blood and creating extreme internal pressure. This is an ADVANCED technique with high injury risk and should only be considered by experienced practitioners.",
  howToUse: [
    "⚠️ ADVANCED TECHNIQUE - Not for beginners",
    "Achieve full erection first",
    "Apply clamp at the base of the penis",
    "Tighten enough to trap blood but not cause pain",
    "Perform kegels to increase engorgement",
    "Limit sessions to 10 minutes MAXIMUM",
    "Multiple short sets are safer than one long set",
    "Release clamp slowly",
  ],
  benefits: ["Intense expansion pressure", "May target girth specifically", "Short session times", "Can be combined with other exercises"],
  cons: [
    "HIGHEST injury risk of all PE methods",
    "Requires full erection",
    "Very easy to overdo",
    "Can cause serious damage quickly",
    "Not suitable for beginners at all",
    "Requires careful monitoring",
  ],
  warnings: [
    "⚠️ EXTREME INJURY RISK - Do not attempt as a beginner",
    "Never clamp for more than 10 minutes",
    "Never sleep with a clamp on",
    "Do not use if you have any vascular conditions",
    "Stop immediately at any sign of numbness",
    "Not recommended by medical professionals",
  ],
  dangers: [
    "Thrombosis (blood clots)",
    "Permanent nerve damage",
    "Tissue necrosis (death)",
    "Severe bruising and hematoma",
    "Long-term erectile dysfunction",
    "Burst blood vessels",
    "Requires emergency medical care if done wrong",
  ],
  safetyTips: [
    "Only attempt after months of other PE experience",
    "Use timer - NEVER exceed 10 minutes",
    "Start with lighter restriction",
    "Have quick-release mechanism ready",
    "Check color and temperature constantly",
    "Take long breaks between sets",
    "Consider whether risks are worth potential benefits",
  ],
  whatToLookFor: [
    "Purple or blue discoloration (release immediately)",
    "Coldness (release immediately)",
    "Numbness (release immediately)",
    "Severe pain (release immediately)",
    "Any throbbing beyond normal",
    "Spots or bruising appearing",
  ],
  experienceLevel: ["advanced"],
};

