# Initialize Android Build Environment and Build APK
# This script sets up Gradle wrapper and builds the APK

Write-Host ""
Write-Host "=== Initializing Android Build Environment ===" -ForegroundColor Cyan
Write-Host ""

# Step 1: Ensure we're in the right directory
if (-not (Test-Path "android")) {
    Write-Host "Error: android folder not found!" -ForegroundColor Red
    exit 1
}

# Step 2: Check if dist exists
if (-not (Test-Path "dist")) {
    Write-Host "Building web app (NSFW direct)..." -ForegroundColor Yellow
    npm run build:nsfw:direct
}

# Step 3: Sync Capacitor
Write-Host "Syncing Capacitor..." -ForegroundColor Yellow
npx cap sync android

# Step 4: Navigate to android folder
Set-Location android

# Step 5: Check for Gradle wrapper, if not, try to initialize it
if (-not (Test-Path "gradlew.bat")) {
    Write-Host ""
    Write-Host "Gradle wrapper not found. Attempting to initialize..." -ForegroundColor Yellow
    
    # Try to use Capacitor to generate wrapper
    Write-Host "Running Capacitor sync to generate Gradle files..." -ForegroundColor Cyan
    Set-Location ..
    npx cap sync android --force
    Set-Location android
    
    # If still no wrapper, provide manual instructions
    if (-not (Test-Path "gradlew.bat")) {
        Write-Host ""
        Write-Host "=== Manual Setup Required ===" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "The Gradle wrapper needs to be generated by Android Studio." -ForegroundColor Cyan
        Write-Host ""
        Write-Host "Please follow these steps:" -ForegroundColor Yellow
        Write-Host "  1. Open Android Studio" -ForegroundColor White
        Write-Host "  2. File > Open > Select the 'android' folder" -ForegroundColor White
        Write-Host "  3. Wait for Gradle sync to complete (this will generate gradlew.bat)" -ForegroundColor White
        Write-Host "  4. Then run this script again, or use:" -ForegroundColor White
        Write-Host "     cd android" -ForegroundColor Cyan
        Write-Host "     .\gradlew.bat assembleDebug" -ForegroundColor Cyan
        Write-Host ""
        
        # Try to open Android Studio
        $studioPaths = @(
            "${env:ProgramFiles}\Android\Android Studio\bin\studio64.exe",
            "${env:ProgramFiles(x86)}\Android\Android Studio\bin\studio64.exe",
            "${env:LOCALAPPDATA}\Programs\Android\Android Studio\bin\studio64.exe",
            "${env:ProgramFiles}\JetBrains\Android Studio\bin\studio64.exe"
        )
        
        foreach ($path in $studioPaths) {
            if (Test-Path $path) {
                Write-Host "Opening Android Studio..." -ForegroundColor Green
                $androidPath = (Resolve-Path "..\android").Path
                Start-Process $path -ArgumentList $androidPath
                break
            }
        }
        
        Set-Location ..
        exit 0
    }
}

# Step 6: Build APK
Write-Host ""
Write-Host "=== Building Android APK ===" -ForegroundColor Green
Write-Host ""

# Build Debug APK
Write-Host "Building Debug APK..." -ForegroundColor Yellow
.\gradlew.bat assembleDebug --no-daemon

if ($LASTEXITCODE -eq 0 -and (Test-Path "app\build\outputs\apk\debug\app-debug.apk")) {
    $debugApk = Get-Item "app\build\outputs\apk\debug\app-debug.apk"
    Write-Host ""
    Write-Host "✓ Debug APK built successfully!" -ForegroundColor Green
    Write-Host "  Location: $($debugApk.FullName)" -ForegroundColor Cyan
    Write-Host "  Size: $([math]::Round($debugApk.Length/1MB, 2)) MB" -ForegroundColor Cyan
    Write-Host ""
}

# Build Release APK
Write-Host "Building Release APK..." -ForegroundColor Yellow
.\gradlew.bat assembleRelease --no-daemon

if ($LASTEXITCODE -eq 0 -and (Test-Path "app\build\outputs\apk\release\app-release.apk")) {
    $releaseApk = Get-Item "app\build\outputs\apk\release\app-release.apk"
    Write-Host ""
    Write-Host "✓ Release APK built successfully!" -ForegroundColor Green
    Write-Host "  Location: $($releaseApk.FullName)" -ForegroundColor Cyan
    Write-Host "  Size: $([math]::Round($releaseApk.Length/1MB, 2)) MB" -ForegroundColor Cyan
    Write-Host ""
} else {
    Write-Host "Release APK build may require signing configuration." -ForegroundColor Yellow
}

Set-Location ..

Write-Host ""
Write-Host "=== Build Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "APK files location:" -ForegroundColor Cyan
Write-Host "  Debug: android\app\build\outputs\apk\debug\app-debug.apk" -ForegroundColor White
if (Test-Path "android\app\build\outputs\apk\release\app-release.apk") {
    Write-Host "  Release: android\app\build\outputs\apk\release\app-release.apk" -ForegroundColor White
}

