export function uuidLike(): string {
  // Not a true UUID; good enough for client-side edit graph IDs.
  // Server-side IDs are generated by Postgres.
  const t = Date.now().toString(16);
  const r = Math.floor(Math.random() * 1e16).toString(16);
  return `${t}-${r}`.slice(0, 36);
}

