export type UUID = string;

export type VideoEditType =
  | "cut"
  | "merge"
  | "transition"
  | "mask"
  | "track"
  | "camera_switch"
  | "filter"
  | "effect"
  | "audio"
  | "other";

export type TransitionType = "cut" | "crossfade" | "dip_to_black";

export type MaskMode = "exclude" | "include";

export type NormalizedPoint = {
  /** 0..100 relative to the rendered cover-rect */
  xPct: number;
  /** 0..100 relative to the rendered cover-rect */
  yPct: number;
};

export type MaskShape =
  | {
      kind: "rect";
      xPct: number;
      yPct: number;
      wPct: number;
      hPct: number;
      radiusPct?: number; // corner radius as % of min(w,h)
    }
  | {
      kind: "polygon";
      points: NormalizedPoint[];
    };

export type MaskKeyframe = {
  atSeconds: number;
  shape: MaskShape;
  /** 0..1 */
  strength?: number;
};

export type MaskTrack = {
  id: UUID;
  name: string;
  mode: MaskMode;
  /** 0..1, preview-only hint; render worker may interpret differently */
  feather?: number;
  /** 0..1, preview-only hint */
  blur?: number;
  keyframes: MaskKeyframe[];
  /**
   * Optional link to an object track (e.g. generated by ML).
   * When present, editor can auto-populate keyframes.
   */
  sourceTrackId?: string;
};

export type CameraSource = {
  /** Camera index (matches `camera_streams.camera_index`) */
  cameraIndex: number;
  /** Direct playable URL for the camera stream */
  videoUrl: string;
  /** Optional storage path (for server-side rendering) */
  storagePath?: string | null;
  /** Seconds offset applied to this camera to keep in sync */
  syncOffsetSeconds?: number;
  /** Optional label */
  label?: string | null;
};

export type CameraSwitchEvent = {
  id: UUID;
  atSeconds: number;
  cameraIndex: number;
  transition: TransitionType;
  transitionDurationMs?: number;
};

export type TimelineSpecV1 = {
  version: 1;
  kind: "multicam";
  /** Target output timeline duration (seconds). */
  durationSeconds: number;
  /** Primary recording id for DB linkage (video_edits.recording_id). */
  baseRecordingId: UUID;
  /** Camera sources available to the edit. */
  sources: CameraSource[];
  /** Camera switch events over time (sorted ascending). */
  cameraSwitches: CameraSwitchEvent[];
  /** Mask tracks (manual and/or tracked). */
  masks: MaskTrack[];
  /**
   * Optional sync markers to help align sources; purely metadata for now.
   * A worker could use this later for smarter sync.
   */
  syncMarkers?: Array<{ id: UUID; atSeconds: number; label?: string }>;
  /** Free-form metadata for future expansion */
  meta?: Record<string, unknown>;
};

export type TimelineSpec = TimelineSpecV1;

export type VideoEditQueueRequest = {
  recordingId: UUID;
  editType: VideoEditType;
  editName?: string;
  timeline: TimelineSpec;
};

export type VideoEditQueueResponse =
  | { ok: true; editId: UUID; status: string }
  | { ok: false; error: string };

