import { supabase } from "./supabase";

export async function seedAchievements() {
  const achievements = [
    {
      code: "first_scan",
      name: "First Scan",
      description: "Complete your first health scan",
      category: "scanning",
      requirement_type: "scan_count",
      requirement_value: 1,
      points: 10,
      badge_color: "#4CAF50",
      icon_name: "Camera",
    },
    {
      code: "scan_streak_7",
      name: "Week Warrior",
      description: "Complete scans for 7 consecutive days",
      category: "streaks",
      requirement_type: "scan_streak",
      requirement_value: 7,
      points: 50,
      badge_color: "#FF9800",
      icon_name: "Flame",
    },
    {
      code: "scan_streak_30",
      name: "Monthly Master",
      description: "Complete scans for 30 consecutive days",
      category: "streaks",
      requirement_type: "scan_streak",
      requirement_value: 30,
      points: 200,
      badge_color: "#E91E63",
      icon_name: "Trophy",
    },
    {
      code: "scan_count_10",
      name: "Dedicated Tracker",
      description: "Complete 10 health scans",
      category: "scanning",
      requirement_type: "scan_count",
      requirement_value: 10,
      points: 25,
      badge_color: "#2196F3",
      icon_name: "Target",
    },
    {
      code: "scan_count_50",
      name: "Health Enthusiast",
      description: "Complete 50 health scans",
      category: "scanning",
      requirement_type: "scan_count",
      requirement_value: 50,
      points: 100,
      badge_color: "#9C27B0",
      icon_name: "Award",
    },
    {
      code: "scan_count_100",
      name: "Century Club",
      description: "Complete 100 health scans",
      category: "scanning",
      requirement_type: "scan_count",
      requirement_value: 100,
      points: 250,
      badge_color: "#FFD700",
      icon_name: "Crown",
    },
    {
      code: "diary_first",
      name: "Journal Starter",
      description: "Create your first health diary entry",
      category: "diary",
      requirement_type: "diary_count",
      requirement_value: 1,
      points: 10,
      badge_color: "#00BCD4",
      icon_name: "BookOpen",
    },
    {
      code: "diary_streak_7",
      name: "Consistent Logger",
      description: "Log diary entries for 7 consecutive days",
      category: "streaks",
      requirement_type: "diary_streak",
      requirement_value: 7,
      points: 50,
      badge_color: "#FF5722",
      icon_name: "Calendar",
    },
    {
      code: "diary_count_30",
      name: "Monthly Journaler",
      description: "Create 30 diary entries",
      category: "diary",
      requirement_type: "diary_count",
      requirement_value: 30,
      points: 75,
      badge_color: "#607D8B",
      icon_name: "Edit",
    },
    {
      code: "profile_complete",
      name: "Profile Pro",
      description: "Complete your user profile",
      category: "profile",
      requirement_type: "profile_complete",
      requirement_value: 1,
      points: 15,
      badge_color: "#795548",
      icon_name: "User",
    },
    {
      code: "first_goal",
      name: "Goal Setter",
      description: "Set your first health goal",
      category: "goals",
      requirement_type: "goal_count",
      requirement_value: 1,
      points: 10,
      badge_color: "#3F51B5",
      icon_name: "Target",
    },
    {
      code: "goal_achieved",
      name: "Goal Crusher",
      description: "Achieve your first health goal",
      category: "goals",
      requirement_type: "goal_achieved",
      requirement_value: 1,
      points: 50,
      badge_color: "#4CAF50",
      icon_name: "CheckCircle",
    },
    {
      code: "pe_session_first",
      name: "PE Beginner",
      description: "Complete your first PE session",
      category: "pe",
      requirement_type: "pe_session_count",
      requirement_value: 1,
      points: 10,
      badge_color: "#F44336",
      icon_name: "Dumbbell",
    },
    {
      code: "pe_session_10",
      name: "PE Regular",
      description: "Complete 10 PE sessions",
      category: "pe",
      requirement_type: "pe_session_count",
      requirement_value: 10,
      points: 50,
      badge_color: "#E91E63",
      icon_name: "Activity",
    },
    {
      code: "pe_session_50",
      name: "PE Dedicated",
      description: "Complete 50 PE sessions",
      category: "pe",
      requirement_type: "pe_session_count",
      requirement_value: 50,
      points: 150,
      badge_color: "#9C27B0",
      icon_name: "Zap",
    },
    {
      code: "education_first",
      name: "Knowledge Seeker",
      description: "Complete your first lesson",
      category: "education",
      requirement_type: "lesson_count",
      requirement_value: 1,
      points: 10,
      badge_color: "#00BCD4",
      icon_name: "BookOpen",
    },
    {
      code: "education_course",
      name: "Course Graduate",
      description: "Complete a full course",
      category: "education",
      requirement_type: "course_complete",
      requirement_value: 1,
      points: 100,
      badge_color: "#009688",
      icon_name: "GraduationCap",
    },
    {
      code: "export_first",
      name: "Data Exporter",
      description: "Export your health data for the first time",
      category: "data",
      requirement_type: "export_count",
      requirement_value: 1,
      points: 15,
      badge_color: "#607D8B",
      icon_name: "Download",
    },
    {
      code: "share_doctor",
      name: "Doctor Connect",
      description: "Share a report with a healthcare provider",
      category: "sharing",
      requirement_type: "share_count",
      requirement_value: 1,
      points: 25,
      badge_color: "#F44336",
      icon_name: "Share2",
    },
    {
      code: "calibration_done",
      name: "Precision Expert",
      description: "Complete measurement calibration",
      category: "scanning",
      requirement_type: "calibration_complete",
      requirement_value: 1,
      points: 20,
      badge_color: "#FF9800",
      icon_name: "Crosshair",
    },
    {
      code: "improvement_5",
      name: "Making Progress",
      description: "Show 5% improvement in any metric",
      category: "progress",
      requirement_type: "improvement_percent",
      requirement_value: 5,
      points: 50,
      badge_color: "#4CAF50",
      icon_name: "TrendingUp",
    },
    {
      code: "improvement_10",
      name: "Significant Gains",
      description: "Show 10% improvement in any metric",
      category: "progress",
      requirement_type: "improvement_percent",
      requirement_value: 10,
      points: 100,
      badge_color: "#8BC34A",
      icon_name: "TrendingUp",
    },
    {
      code: "community_first",
      name: "Community Member",
      description: "Make your first forum post",
      category: "community",
      requirement_type: "forum_post_count",
      requirement_value: 1,
      points: 10,
      badge_color: "#03A9F4",
      icon_name: "MessageSquare",
    },
    {
      code: "early_adopter",
      name: "Early Adopter",
      description: "Join GrowthTracker in its first year",
      category: "special",
      requirement_type: "signup_date",
      requirement_value: 1,
      points: 100,
      badge_color: "#FFD700",
      icon_name: "Star",
      is_premium: true,
    },
    {
      code: "premium_member",
      name: "Premium Member",
      description: "Upgrade to a premium subscription",
      category: "special",
      requirement_type: "subscription",
      requirement_value: 1,
      points: 50,
      badge_color: "#9C27B0",
      icon_name: "Crown",
      is_premium: true,
    },
  ];

  const { error } = await supabase
    .from("achievement_definitions")
    .upsert(achievements, { onConflict: "code" });
  if (error) console.error("Error seeding achievements:", error.message);
  else console.log(`✅ Seeded ${achievements.length} achievements`);
}
