import "dotenv/config";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "../src/integrations/supabase/types";

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const ADMIN_EMAIL = process.env.ADMIN_SUPER_EMAIL || "n8ter8@gmail.com";

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY environment variables.");
  process.exit(1);
}

const supabase = createClient<Database>(SUPABASE_URL, SERVICE_ROLE_KEY);

const seedRoles = async () => {
  const { error } = await supabase.from("roles").upsert(
    [
      { name: "super_admin", description: "Full administrative control" },
      { name: "clinician", description: "Medical professional access" },
      { name: "patient", description: "Standard end user" },
    ],
    { onConflict: "name" },
  );

  if (error) throw error;
};

const getRoleId = async (roleName: string) => {
  const { data, error } = await supabase.from("roles").select("id").eq("name", roleName).single();
  if (error || !data) throw error || new Error(`Role ${roleName} not found.`);
  return data.id;
};

const assignSuperAdmin = async (roleId: string) => {
  const { data: userResult, error } = await supabase.auth.admin.getUserByEmail(ADMIN_EMAIL);

  if (error) {
    throw error;
  }

  const user = userResult.user;
  if (!user) {
    console.warn(
      `Admin user '${ADMIN_EMAIL}' not found. Create it in Supabase Dashboard then rerun this seed.`,
    );
    return;
  }

  const { error: upsertError } = await supabase
    .from("user_roles")
    .upsert(
      { user_id: user.id, role_id: roleId, assigned_by: user.id },
      { onConflict: "user_id,role_id" },
    );

  if (upsertError) throw upsertError;

  console.log(`Granted 'super_admin' role to ${ADMIN_EMAIL}`);
};

const seedDemoData = async (roleId: string) => {
  const { data: userResult } = await supabase.auth.admin.listUsers({ perPage: 1 });
  const fallbackUser = userResult.users?.[0];

  if (!fallbackUser) {
    console.warn("No users available to seed health diary data. Skipping.");
    return;
  }

  const userId = fallbackUser.id;

  const { error: diaryError } = await supabase.from("health_diary").upsert([
    {
      user_id: userId,
      entry_date: new Date().toISOString().slice(0, 10),
      length: 13.4,
      circumference: 11.2,
      curvature_angle: 12.5,
      curvature_direction: "Dorsal",
      symptoms: ["tightness", "tenderness"],
      pain_level: 3,
      notes: "Baseline entry generated by seed script.",
    },
  ]);

  if (diaryError) throw diaryError;

  console.log("Inserted sample diary data for first available user.");
};

(async () => {
  try {
    await seedRoles();
    const superAdminRoleId = await getRoleId("super_admin");
    await assignSuperAdmin(superAdminRoleId);
    await seedDemoData(superAdminRoleId);
    console.log("Seed complete.");
    process.exit(0);
  } catch (error) {
    console.error("Seed failed:", error);
    process.exit(1);
  }
})();
