-- Migration: Expand NSFW DLC add-ons catalog (store + entitlements)
-- Purpose:
-- - Add additional NSFW DLC add-ons to dlc_packages (beyond the original 7-package baseline)
-- - Keep idempotent behavior (safe to re-run)
-- Notes:
-- - Does not delete or deactivate existing packages
-- - Stripe IDs are configured separately via admin UI (stripe_price_id/stripe_product_id columns already exist)

WITH catalog AS (
  SELECT * FROM (VALUES
    (
      'dlc-analytics',
      'Wellness Analytics',
      'individual',
      'Adult wellness analytics, reports, and partner-aware insights.',
      'Unlock wellness analytics: trend analysis, reports, partner sync insights, and richer dashboards. Designed for adult wellness tracking with privacy-first defaults.',
      'See patterns. Improve outcomes.',
      9.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":8.99,"GBP":7.99,"CAD":12.99}'::jsonb,
      '[
        {"id":"wellness_analytics","name":"Wellness Analytics","description":"Detailed intimate wellness tracking","icon":"BarChart","category":"analytics"},
        {"id":"partner_sync","name":"Partner Sync","description":"Sync data with your partner","icon":"Users","category":"analytics"},
        {"id":"intimate_reports","name":"Intimate Reports","description":"Generate detailed wellness reports","icon":"FileText","category":"analytics"},
        {"id":"trend_analysis","name":"Trend Analysis","description":"Analyze patterns and trends","icon":"TrendingUp","category":"analytics"},
        {"id":"relationship_insights","name":"Relationship Insights","description":"AI-powered relationship insights","icon":"Lightbulb","category":"analytics"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.27',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      8,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-community',
      'Private Community',
      'individual',
      'Private adult community forum, groups, and expert Q&A.',
      'Unlock community features: private forum, support groups, expert Q&A, and member-only content. Built with anonymity controls, redaction options, and moderation workflows.',
      'Connect safely, learn faster',
      9.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":8.99,"GBP":7.99,"CAD":12.99}'::jsonb,
      '[
        {"id":"private_forum","name":"Private Forum","description":"Access to private adult community forum","icon":"MessageCircle","category":"community"},
        {"id":"private_groups","name":"Private Groups","description":"Join or create private discussion groups","icon":"Users","category":"community"},
        {"id":"expert_qa","name":"Expert Q&A","description":"Ask questions to verified experts","icon":"HelpCircle","category":"community"},
        {"id":"creator_marketplace","name":"Creator Marketplace","description":"Access premium content from creators","icon":"ShoppingBag","category":"marketplace"},
        {"id":"exclusive_content","name":"Exclusive Content","description":"Members-only exclusive content","icon":"Lock","category":"community"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.27',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      9,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-topics-library',
      'Topics Library',
      'individual',
      'Adult educational topics library with privacy-safe presentation.',
      'Unlock the Topics Library module. Topic packs add specific content gates (Power Dynamics, Tantric, Roleplay, etc.).',
      'Education-first library',
      2.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":2.49,"GBP":2.29,"CAD":3.99}'::jsonb,
      '[
        {"id":"topics_library","name":"Topics Library","description":"Access the Topics Library module","icon":"BookOpen","category":"topics"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.27',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      10,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-nsfw-scanner',
      'NSFW Scanner Mode',
      'individual',
      'Adult-only scanning mode with explicit-content detection controls.',
      'Unlock NSFW Scanner Mode: on-device explicit-content detection controls, thresholds, and safety policy options. Disabled by default; you must enable it in Settings after age verification.',
      'Adult-only scanning mode',
      6.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":5.99,"GBP":5.49,"CAD":8.99}'::jsonb,
      '[
        {"id":"nsfw_scanner_mode","name":"NSFW Scanner Mode","description":"Enable adult-only scanning mode and policy controls","icon":"Shield","category":"advanced"},
        {"id":"explicit_content_detection","name":"Explicit Content Detection","description":"On-device explicit content detection (NSFWJS + TFJS)","icon":"Eye","category":"advanced"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.27',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      11,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-advanced-nsfw-detection',
      'Advanced NSFW Detection Modes',
      'subscription',
      'Advanced detection, ensemble scoring, and detailed breakdowns (adult).',
      'Unlock advanced NSFW detection modes: configurable model selection, ensemble scoring, and opt-in detection history (no image content stored).',
      'More control. More confidence.',
      14.99::DECIMAL(10,2),
      'subscription',
      'monthly',
      '{"EUR":13.99,"GBP":12.99,"CAD":19.99}'::jsonb,
      '[
        {"id":"advanced_nsfw_detection","name":"Advanced NSFW Detection Modes","description":"Multi-model detection, ensemble scoring, and detailed breakdowns","icon":"Sparkles","category":"advanced"},
        {"id":"nsfw_detection_history","name":"Detection History","description":"Store and review past detection results (opt-in; no image content stored)","icon":"BarChart","category":"advanced"},
        {"id":"nsfw_comparison_mode","name":"Comparison Mode","description":"Compare results across enabled models and thresholds","icon":"Columns","category":"advanced"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.27',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      12,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    )
  ) AS t(
    package_id,
    package_name,
    package_type,
    safe_description,
    full_description,
    marketing_tagline,
    price_usd,
    price_type,
    subscription_interval,
    regional_pricing,
    features,
    included_packages,
    version,
    content_version,
    min_app_version,
    max_app_version,
    content_changelog,
    is_active,
    is_featured,
    display_order,
    content_rating,
    preview_images,
    preview_video_url,
    localized_names,
    localized_descriptions
  )
)
INSERT INTO public.dlc_packages (
  package_id,
  package_name,
  package_type,
  safe_description,
  full_description,
  marketing_tagline,
  price_usd,
  price_type,
  subscription_interval,
  regional_pricing,
  features,
  included_packages,
  version,
  content_version,
  min_app_version,
  max_app_version,
  content_changelog,
  is_active,
  is_featured,
  display_order,
  content_rating,
  preview_images,
  preview_video_url,
  localized_names,
  localized_descriptions
)
SELECT
  package_id,
  package_name,
  package_type,
  safe_description,
  full_description,
  marketing_tagline,
  price_usd,
  price_type,
  subscription_interval,
  regional_pricing,
  features,
  included_packages,
  version,
  content_version,
  min_app_version,
  max_app_version,
  content_changelog,
  is_active,
  is_featured,
  display_order,
  content_rating,
  preview_images,
  preview_video_url,
  localized_names,
  localized_descriptions
FROM catalog
WHERE public.is_nsfw_enabled()
ON CONFLICT (package_id) DO UPDATE SET
  package_name = EXCLUDED.package_name,
  package_type = EXCLUDED.package_type,
  safe_description = EXCLUDED.safe_description,
  full_description = EXCLUDED.full_description,
  marketing_tagline = EXCLUDED.marketing_tagline,
  price_usd = EXCLUDED.price_usd,
  price_type = EXCLUDED.price_type,
  subscription_interval = EXCLUDED.subscription_interval,
  regional_pricing = EXCLUDED.regional_pricing,
  features = EXCLUDED.features,
  included_packages = EXCLUDED.included_packages,
  version = EXCLUDED.version,
  content_version = EXCLUDED.content_version,
  min_app_version = EXCLUDED.min_app_version,
  max_app_version = EXCLUDED.max_app_version,
  content_changelog = EXCLUDED.content_changelog,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  display_order = EXCLUDED.display_order,
  content_rating = EXCLUDED.content_rating,
  preview_images = EXCLUDED.preview_images,
  preview_video_url = EXCLUDED.preview_video_url,
  localized_names = EXCLUDED.localized_names,
  localized_descriptions = EXCLUDED.localized_descriptions,
  updated_at = now();

