-- Migration: DLC catalog alignment + Stripe columns
-- Purpose:
-- - Ensure dlc_packages matches the in-app DLCRegistry catalog (7 packages)
-- - Add optional Stripe identifiers for packages (future-proof)
-- Notes:
-- - Idempotent (safe to re-run)
-- - Does not delete or drop existing data

-- Optional Stripe identifiers
ALTER TABLE IF EXISTS dlc_packages
  ADD COLUMN IF NOT EXISTS stripe_product_id TEXT;

ALTER TABLE IF EXISTS dlc_packages
  ADD COLUMN IF NOT EXISTS stripe_price_id TEXT;

CREATE INDEX IF NOT EXISTS idx_dlc_packages_stripe_product_id ON dlc_packages(stripe_product_id);
CREATE INDEX IF NOT EXISTS idx_dlc_packages_stripe_price_id ON dlc_packages(stripe_price_id);

-- Upsert canonical package catalog
-- (Keeps existing rows, updates fields to match current catalog definition)
WITH catalog AS (
  SELECT * FROM (VALUES
    (
      'dlc-positions',
      'Positions Collection',
      'individual',
      'Comprehensive guide to partner connection techniques with visual instructions and expert tips for adults',
      '100+ positions with detailed instructions, images, difficulty ratings, and expert tips. Includes favorites, playlists, and advanced filtering.',
      'Explore 100+ ways to connect',
      9.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":8.99,"GBP":7.99,"CAD":12.99}'::jsonb,
      '[
        {"id":"positions_gallery","name":"Positions Gallery","description":"100+ positions with visual guides","icon":"Heart","category":"positions"},
        {"id":"position_details","name":"Position Details","description":"Detailed instructions and tips","icon":"Info","category":"positions"},
        {"id":"position_favorites","name":"Favorites","description":"Save and organize favorites","icon":"Star","category":"positions"},
        {"id":"position_filters","name":"Advanced Filters","description":"Filter by difficulty, category, and more","icon":"Filter","category":"positions"},
        {"id":"position_playlists","name":"Position Playlists","description":"Create custom playlists","icon":"List","category":"positions"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2024.12.1',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      1,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{"es":"Colección de Posiciones","de":"Positionssammlung","fr":"Collection de Positions"}'::jsonb,
      '{"es":"Guía completa de técnicas de conexión con instrucciones visuales","de":"Umfassender Leitfaden für Verbindungstechniken mit visuellen Anleitungen","fr":"Guide complet des techniques de connexion avec instructions visuelles"}'::jsonb
    ),
    (
      'dlc-videos',
      'Video Library',
      'individual',
      'Premium video library featuring expert demonstrations and educational wellness content for adults',
      'Educational video library with HD streaming, offline downloads, playlists, and progress tracking.',
      'Learn from the experts',
      14.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":12.99,"GBP":11.99,"CAD":18.99}'::jsonb,
      '[
        {"id":"video_library","name":"Video Library","description":"Premium adult video content library","icon":"Video","category":"videos"},
        {"id":"video_streaming","name":"HD Streaming","description":"Stream in high definition","icon":"Play","category":"videos"},
        {"id":"video_downloads","name":"Offline Downloads","description":"Download for offline viewing","icon":"Download","category":"videos"},
        {"id":"video_playlists","name":"Video Playlists","description":"Create and manage playlists","icon":"List","category":"videos"},
        {"id":"video_progress","name":"Progress Tracking","description":"Track viewing progress","icon":"CheckCircle","category":"videos"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2024.12.1',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      2,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-intimate',
      'Intimate Experience Pack',
      'bundle',
      'Complete intimate wellness toolkit with guides, tracking, and partner features',
      'Positions Collection + wellness analytics + partner sync + relationship insights + reports.',
      'The complete couple''s toolkit',
      14.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":12.99,"GBP":11.99,"CAD":18.99}'::jsonb,
      '[
        {"id":"positions_gallery","name":"Positions Gallery","description":"100+ positions with visual guides","icon":"Heart","category":"positions"},
        {"id":"position_details","name":"Position Details","description":"Detailed instructions and tips","icon":"Info","category":"positions"},
        {"id":"position_favorites","name":"Favorites","description":"Save and organize favorites","icon":"Star","category":"positions"},
        {"id":"position_filters","name":"Advanced Filters","description":"Filter by difficulty, category, and more","icon":"Filter","category":"positions"},
        {"id":"position_playlists","name":"Position Playlists","description":"Create custom playlists","icon":"List","category":"positions"},
        {"id":"wellness_analytics","name":"Wellness Analytics","description":"Detailed wellness tracking","icon":"BarChart","category":"analytics"},
        {"id":"partner_sync","name":"Partner Sync","description":"Sync data with your partner","icon":"Users","category":"analytics"},
        {"id":"intimate_reports","name":"Intimate Reports","description":"Generate detailed reports","icon":"FileText","category":"analytics"},
        {"id":"trend_analysis","name":"Trend Analysis","description":"Analyze patterns and trends","icon":"TrendingUp","category":"analytics"},
        {"id":"relationship_insights","name":"Relationship Insights","description":"Insights and recommendations","icon":"Lightbulb","category":"analytics"}
      ]'::jsonb,
      ARRAY['dlc-positions']::TEXT[],
      '1.0.0',
      '2024.12.1',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      true,
      3,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-creator',
      'Creator & Community Pack',
      'bundle',
      'Join our exclusive community with premium content from verified wellness experts',
      'Video Library + private forum + expert Q&A + creator marketplace + exclusive content.',
      'Join the community',
      19.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":17.99,"GBP":15.99,"CAD":24.99}'::jsonb,
      '[
        {"id":"video_library","name":"Video Library","description":"Premium adult video content library","icon":"Video","category":"videos"},
        {"id":"video_streaming","name":"HD Streaming","description":"Stream in high definition","icon":"Play","category":"videos"},
        {"id":"video_downloads","name":"Offline Downloads","description":"Download for offline viewing","icon":"Download","category":"videos"},
        {"id":"video_playlists","name":"Video Playlists","description":"Create and manage playlists","icon":"List","category":"videos"},
        {"id":"video_progress","name":"Progress Tracking","description":"Track viewing progress","icon":"CheckCircle","category":"videos"},
        {"id":"private_forum","name":"Private Forum","description":"Private community forum","icon":"MessageCircle","category":"community"},
        {"id":"private_groups","name":"Private Groups","description":"Join or create private groups","icon":"Users","category":"community"},
        {"id":"expert_qa","name":"Expert Q&A","description":"Ask questions to verified experts","icon":"HelpCircle","category":"community"},
        {"id":"creator_marketplace","name":"Creator Marketplace","description":"Premium content from creators","icon":"ShoppingBag","category":"marketplace"},
        {"id":"exclusive_content","name":"Exclusive Content","description":"Members-only content","icon":"Lock","category":"community"}
      ]'::jsonb,
      ARRAY['dlc-videos']::TEXT[],
      '1.0.0',
      '2024.12.1',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      4,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-advanced',
      'Advanced Features Pack',
      'bundle',
      'Premium suite of advanced features for the complete intimate experience',
      'Positions + Videos + Multi-camera recording + Date planner + AI companion + Partner sync.',
      'Unlock everything',
      29.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":26.99,"GBP":23.99,"CAD":37.99}'::jsonb,
      '[
        {"id":"positions_gallery","name":"Positions Gallery","description":"100+ positions with visual guides","icon":"Heart","category":"positions"},
        {"id":"position_details","name":"Position Details","description":"Detailed instructions and tips","icon":"Info","category":"positions"},
        {"id":"position_favorites","name":"Favorites","description":"Save and organize favorites","icon":"Star","category":"positions"},
        {"id":"position_filters","name":"Advanced Filters","description":"Filter by difficulty, category, and more","icon":"Filter","category":"positions"},
        {"id":"position_playlists","name":"Position Playlists","description":"Create custom playlists","icon":"List","category":"positions"},
        {"id":"video_library","name":"Video Library","description":"Premium adult video content library","icon":"Video","category":"videos"},
        {"id":"video_streaming","name":"HD Streaming","description":"Stream in high definition","icon":"Play","category":"videos"},
        {"id":"video_downloads","name":"Offline Downloads","description":"Download for offline viewing","icon":"Download","category":"videos"},
        {"id":"video_playlists","name":"Video Playlists","description":"Create and manage playlists","icon":"List","category":"videos"},
        {"id":"video_progress","name":"Progress Tracking","description":"Track viewing progress","icon":"CheckCircle","category":"videos"},
        {"id":"multi_camera","name":"Multi-Camera Recording","description":"Record with multiple cameras","icon":"Camera","category":"advanced"},
        {"id":"intimate_dates","name":"Intimate Date Planner","description":"Plan and schedule dates","icon":"Calendar","category":"advanced"},
        {"id":"ai_companion","name":"AI Companion Chat","description":"AI companion suggestions","icon":"MessageSquare","category":"advanced"},
        {"id":"partner_video_sync","name":"Partner Video Sync","description":"Sync recordings with partner","icon":"Link","category":"advanced"}
      ]'::jsonb,
      ARRAY['dlc-positions','dlc-videos']::TEXT[],
      '1.0.0',
      '2024.12.1',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      true,
      5,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-complete',
      'Ultimate Complete Pack',
      'bundle',
      'The complete experience - all premium features unlocked forever with lifetime access',
      'Everything included: Positions, Videos, Analytics, Community, Advanced features. Lifetime access and updates.',
      'The ultimate experience',
      39.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":35.99,"GBP":31.99,"CAD":49.99}'::jsonb,
      '[
        {"id":"positions_gallery","name":"Positions Gallery","description":"100+ positions with visual guides","icon":"Heart","category":"positions"},
        {"id":"position_details","name":"Position Details","description":"Detailed instructions and tips","icon":"Info","category":"positions"},
        {"id":"position_favorites","name":"Favorites","description":"Save and organize favorites","icon":"Star","category":"positions"},
        {"id":"position_filters","name":"Advanced Filters","description":"Filter by difficulty, category, and more","icon":"Filter","category":"positions"},
        {"id":"position_playlists","name":"Position Playlists","description":"Create custom playlists","icon":"List","category":"positions"},
        {"id":"video_library","name":"Video Library","description":"Premium adult video content library","icon":"Video","category":"videos"},
        {"id":"video_streaming","name":"HD Streaming","description":"Stream in high definition","icon":"Play","category":"videos"},
        {"id":"video_downloads","name":"Offline Downloads","description":"Download for offline viewing","icon":"Download","category":"videos"},
        {"id":"video_playlists","name":"Video Playlists","description":"Create and manage playlists","icon":"List","category":"videos"},
        {"id":"video_progress","name":"Progress Tracking","description":"Track viewing progress","icon":"CheckCircle","category":"videos"},
        {"id":"wellness_analytics","name":"Wellness Analytics","description":"Detailed wellness tracking","icon":"BarChart","category":"analytics"},
        {"id":"partner_sync","name":"Partner Sync","description":"Sync data with your partner","icon":"Users","category":"analytics"},
        {"id":"intimate_reports","name":"Intimate Reports","description":"Generate detailed reports","icon":"FileText","category":"analytics"},
        {"id":"trend_analysis","name":"Trend Analysis","description":"Analyze patterns and trends","icon":"TrendingUp","category":"analytics"},
        {"id":"relationship_insights","name":"Relationship Insights","description":"Insights and recommendations","icon":"Lightbulb","category":"analytics"},
        {"id":"private_forum","name":"Private Forum","description":"Private community forum","icon":"MessageCircle","category":"community"},
        {"id":"private_groups","name":"Private Groups","description":"Join or create private groups","icon":"Users","category":"community"},
        {"id":"expert_qa","name":"Expert Q&A","description":"Ask questions to verified experts","icon":"HelpCircle","category":"community"},
        {"id":"creator_marketplace","name":"Creator Marketplace","description":"Premium content from creators","icon":"ShoppingBag","category":"marketplace"},
        {"id":"exclusive_content","name":"Exclusive Content","description":"Members-only content","icon":"Lock","category":"community"},
        {"id":"multi_camera","name":"Multi-Camera Recording","description":"Record with multiple cameras","icon":"Camera","category":"advanced"},
        {"id":"intimate_dates","name":"Intimate Date Planner","description":"Plan and schedule dates","icon":"Calendar","category":"advanced"},
        {"id":"ai_companion","name":"AI Companion Chat","description":"AI companion suggestions","icon":"MessageSquare","category":"advanced"},
        {"id":"partner_video_sync","name":"Partner Video Sync","description":"Sync recordings with partner","icon":"Link","category":"advanced"}
      ]'::jsonb,
      ARRAY['dlc-positions','dlc-videos','dlc-intimate','dlc-creator','dlc-advanced']::TEXT[],
      '1.0.0',
      '2024.12.1',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      true,
      6,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-subscription',
      'All-Access Pass',
      'subscription',
      'Full access to everything with continuous updates and priority support',
      'Subscription access to all DLC features and updates. Cancel anytime.',
      'All access, always updated',
      9.99::DECIMAL(10,2),
      'subscription',
      'monthly',
      '{"EUR":8.99,"GBP":7.99,"CAD":12.99}'::jsonb,
      '[
        {"id":"positions_gallery","name":"Positions Gallery","description":"100+ positions with visual guides","icon":"Heart","category":"positions"},
        {"id":"video_library","name":"Video Library","description":"Premium adult video content library","icon":"Video","category":"videos"},
        {"id":"wellness_analytics","name":"Wellness Analytics","description":"Detailed wellness tracking","icon":"BarChart","category":"analytics"},
        {"id":"private_forum","name":"Private Forum","description":"Private community forum","icon":"MessageCircle","category":"community"},
        {"id":"multi_camera","name":"Multi-Camera Recording","description":"Record with multiple cameras","icon":"Camera","category":"advanced"}
      ]'::jsonb,
      ARRAY['dlc-positions','dlc-videos','dlc-intimate','dlc-creator','dlc-advanced']::TEXT[],
      '1.0.0',
      '2024.12.1',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      7,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    )
  ) AS t(
    package_id,
    package_name,
    package_type,
    safe_description,
    full_description,
    marketing_tagline,
    price_usd,
    price_type,
    subscription_interval,
    regional_pricing,
    features,
    included_packages,
    version,
    content_version,
    min_app_version,
    max_app_version,
    content_changelog,
    is_active,
    is_featured,
    display_order,
    content_rating,
    preview_images,
    preview_video_url,
    localized_names,
    localized_descriptions
  )
)
INSERT INTO dlc_packages (
  package_id,
  package_name,
  package_type,
  safe_description,
  full_description,
  marketing_tagline,
  price_usd,
  price_type,
  subscription_interval,
  regional_pricing,
  features,
  included_packages,
  version,
  content_version,
  min_app_version,
  max_app_version,
  content_changelog,
  is_active,
  is_featured,
  display_order,
  content_rating,
  preview_images,
  preview_video_url,
  localized_names,
  localized_descriptions
)
SELECT
  package_id,
  package_name,
  package_type,
  safe_description,
  full_description,
  marketing_tagline,
  price_usd,
  price_type,
  subscription_interval,
  regional_pricing,
  features,
  included_packages,
  version,
  content_version,
  min_app_version,
  max_app_version,
  content_changelog,
  is_active,
  is_featured,
  display_order,
  content_rating,
  preview_images,
  preview_video_url,
  localized_names,
  localized_descriptions
FROM catalog
ON CONFLICT (package_id) DO UPDATE SET
  package_name = EXCLUDED.package_name,
  package_type = EXCLUDED.package_type,
  safe_description = EXCLUDED.safe_description,
  full_description = EXCLUDED.full_description,
  marketing_tagline = EXCLUDED.marketing_tagline,
  price_usd = EXCLUDED.price_usd,
  price_type = EXCLUDED.price_type,
  subscription_interval = EXCLUDED.subscription_interval,
  regional_pricing = EXCLUDED.regional_pricing,
  features = EXCLUDED.features,
  included_packages = EXCLUDED.included_packages,
  version = EXCLUDED.version,
  content_version = EXCLUDED.content_version,
  min_app_version = EXCLUDED.min_app_version,
  max_app_version = EXCLUDED.max_app_version,
  content_changelog = EXCLUDED.content_changelog,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  display_order = EXCLUDED.display_order,
  content_rating = EXCLUDED.content_rating,
  preview_images = EXCLUDED.preview_images,
  preview_video_url = EXCLUDED.preview_video_url,
  localized_names = EXCLUDED.localized_names,
  localized_descriptions = EXCLUDED.localized_descriptions,
  updated_at = NOW();

