-- Migration: Enabled packages catalog expansion (requested list)
-- Purpose:
-- - Add missing "enabled packages" into dlc_packages
-- - Align naming for dlc-complete to "Complete DLC Bundle"
-- Notes:
-- - Idempotent (safe to re-run)
-- - Does not delete existing data

WITH catalog AS (
  SELECT * FROM (VALUES
    -- Rename/align: Complete DLC Bundle (existing id)
    (
      'dlc-complete',
      'Complete DLC Bundle',
      'bundle',
      'Everything unlocked with lifetime access and updates (adult).',
      'Every feature, every piece of content, lifetime access. Includes all current and future content updates. The best value for the complete experience.',
      'The complete bundle',
      39.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":35.99,"GBP":31.99,"CAD":49.99}'::jsonb,
      NULL::jsonb,
      ARRAY['dlc-positions','dlc-videos','dlc-intimate','dlc-creator','dlc-advanced']::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      true,
      6,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),

    -- Standalone: AI Intimacy Coach (reuses ai_companion feature)
    (
      'dlc-ai-intimacy-coach',
      'AI Intimacy Coach',
      'individual',
      'AI-powered intimacy coaching and relationship guidance for adults.',
      'Unlock AI Intimacy Coach: private coaching sessions, conversation prompts, and relationship guidance. Includes session history and user-controlled privacy settings.',
      'Private, judgment-free coaching',
      7.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":6.99,"GBP":6.49,"CAD":9.99}'::jsonb,
      '[
        {"id":"ai_companion","name":"AI Companion Chat","description":"Chat with an AI companion for suggestions","icon":"MessageSquare","category":"advanced"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      13,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),

    -- Standalone: Intimate Date Ideas (reuses intimate_dates feature)
    (
      'dlc-intimate-date-ideas',
      'Intimate Date Ideas',
      'individual',
      'Plan and coordinate intimate dates with proposals and partner responses (adult).',
      'Unlock Intimate Date Ideas: date proposals, planning, partner response flow, and a private history of plans. Requires a real partner user id for coordination.',
      'Plan better nights',
      5.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":5.49,"GBP":4.99,"CAD":7.99}'::jsonb,
      '[
        {"id":"intimate_dates","name":"Intimate Date Ideas","description":"Plan and schedule intimate dates","icon":"Calendar","category":"advanced"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      14,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),

    -- PE Routines tiers (non-image content; still adult wellness context)
    (
      'dlc-pe-routines-beginner',
      'PE Routines - Beginner',
      'individual',
      'Beginner PE routine templates with safety-first guidance.',
      'Unlock the PE Routine Builder with beginner templates and progression. Includes exercise library and session tracking.',
      'Start safely',
      4.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":4.49,"GBP":3.99,"CAD":6.49}'::jsonb,
      '[
        {"id":"pe_routines","name":"PE Routines","description":"Unlock the PE Routine Builder experience","icon":"Dumbbell","category":"advanced"},
        {"id":"pe_routines_beginner","name":"PE Routines - Beginner","description":"Beginner routine templates and guided progression","icon":"Sparkles","category":"advanced"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      15,
      'adult',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-pe-routines-intermediate',
      'PE Routines - Intermediate',
      'individual',
      'Intermediate PE routines with enhanced progression options.',
      'Unlock intermediate routines and progression controls in the PE Routine Builder. Includes all beginner content.',
      'Build consistency',
      6.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":6.49,"GBP":5.99,"CAD":8.99}'::jsonb,
      '[
        {"id":"pe_routines","name":"PE Routines","description":"Unlock the PE Routine Builder experience","icon":"Dumbbell","category":"advanced"},
        {"id":"pe_routines_intermediate","name":"PE Routines - Intermediate","description":"Intermediate routine templates and progression options","icon":"TrendingUp","category":"advanced"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      16,
      'adult',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-pe-routines-advanced',
      'PE Routines - Advanced',
      'individual',
      'Advanced PE routines (including pumping-focused options) for experienced users.',
      'Unlock advanced routines and progression controls in the PE Routine Builder. Includes beginner + intermediate content.',
      'Train like a pro',
      9.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":8.99,"GBP":7.99,"CAD":12.99}'::jsonb,
      '[
        {"id":"pe_routines","name":"PE Routines","description":"Unlock the PE Routine Builder experience","icon":"Dumbbell","category":"advanced"},
        {"id":"pe_routines_advanced","name":"PE Routines - Advanced","description":"Advanced routines and progression controls","icon":"Zap","category":"advanced"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      17,
      'adult',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-pe-routines',
      'PE Routines',
      'bundle',
      'Full PE routine library (beginner → advanced).',
      'Unlock all PE routine tiers: beginner, intermediate, and advanced, plus progression controls and full routine browsing.',
      'All routine tiers',
      14.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":13.99,"GBP":12.99,"CAD":18.99}'::jsonb,
      '[
        {"id":"pe_routines","name":"PE Routines","description":"Unlock the PE Routine Builder experience","icon":"Dumbbell","category":"advanced"},
        {"id":"pe_routines_advanced","name":"PE Routines - Advanced","description":"Advanced routines and progression controls","icon":"Zap","category":"advanced"}
      ]'::jsonb,
      ARRAY['dlc-pe-routines-beginner','dlc-pe-routines-intermediate','dlc-pe-routines-advanced']::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      true,
      18,
      'adult',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),

    -- Positions Gallery tiers (curation flags used by UI)
    (
      'dlc-positions-gallery-beginner',
      'Positions Gallery - Beginner',
      'individual',
      'Beginner-friendly positions curation and simplified navigation (adult).',
      'Unlock Positions Gallery with beginner curation and simplified navigation. Includes core gallery features and safety-first guidance.',
      'Beginner-friendly curation',
      4.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":4.49,"GBP":3.99,"CAD":6.49}'::jsonb,
      '[
        {"id":"positions_gallery","name":"Positions Gallery","description":"100+ positions with visual guides","icon":"Heart","category":"positions"},
        {"id":"position_details","name":"Position Details","description":"Detailed instructions and tips for each position","icon":"Info","category":"positions"},
        {"id":"position_favorites","name":"Favorites","description":"Save and organize your favorite positions","icon":"Star","category":"positions"},
        {"id":"position_filters","name":"Advanced Filters","description":"Filter by difficulty, category, and more","icon":"Filter","category":"positions"},
        {"id":"position_playlists","name":"Position Playlists","description":"Create custom position playlists","icon":"List","category":"positions"},
        {"id":"positions_gallery_beginner","name":"Positions Gallery - Beginner","description":"Beginner-friendly positions curation","icon":"Sparkles","category":"positions"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      19,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-positions-gallery-intermediate',
      'Positions Gallery - Intermediate',
      'individual',
      'Intermediate positions curation with enhanced filters (adult).',
      'Unlock Positions Gallery with intermediate curation and enhanced filtering. Includes all beginner curation.',
      'Enhanced filters + curation',
      6.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":6.49,"GBP":5.99,"CAD":8.99}'::jsonb,
      '[
        {"id":"positions_gallery","name":"Positions Gallery","description":"100+ positions with visual guides","icon":"Heart","category":"positions"},
        {"id":"position_details","name":"Position Details","description":"Detailed instructions and tips for each position","icon":"Info","category":"positions"},
        {"id":"position_favorites","name":"Favorites","description":"Save and organize your favorite positions","icon":"Star","category":"positions"},
        {"id":"position_filters","name":"Advanced Filters","description":"Filter by difficulty, category, and more","icon":"Filter","category":"positions"},
        {"id":"position_playlists","name":"Position Playlists","description":"Create custom position playlists","icon":"List","category":"positions"},
        {"id":"positions_gallery_intermediate","name":"Positions Gallery - Intermediate","description":"Intermediate positions curation","icon":"TrendingUp","category":"positions"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      20,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    ),
    (
      'dlc-positions-gallery-advanced',
      'Positions Gallery - Advanced',
      'individual',
      'Advanced positions curation including expert-level entries (adult).',
      'Unlock Positions Gallery with advanced curation, expert-level entries, and the richest filtering experience. Includes all beginner + intermediate curation.',
      'Advanced curation',
      9.99::DECIMAL(10,2),
      'one_time',
      NULL::TEXT,
      '{"EUR":8.99,"GBP":7.99,"CAD":12.99}'::jsonb,
      '[
        {"id":"positions_gallery","name":"Positions Gallery","description":"100+ positions with visual guides","icon":"Heart","category":"positions"},
        {"id":"position_details","name":"Position Details","description":"Detailed instructions and tips for each position","icon":"Info","category":"positions"},
        {"id":"position_favorites","name":"Favorites","description":"Save and organize your favorite positions","icon":"Star","category":"positions"},
        {"id":"position_filters","name":"Advanced Filters","description":"Filter by difficulty, category, and more","icon":"Filter","category":"positions"},
        {"id":"position_playlists","name":"Position Playlists","description":"Create custom position playlists","icon":"List","category":"positions"},
        {"id":"positions_gallery_advanced","name":"Positions Gallery - Advanced","description":"Advanced positions curation","icon":"Flame","category":"positions"}
      ]'::jsonb,
      NULL::TEXT[],
      '1.0.0',
      '2025.12.28',
      '1.0.0',
      NULL::TEXT,
      '[]'::jsonb,
      true,
      false,
      21,
      '18+',
      NULL::TEXT[],
      NULL::TEXT,
      '{}'::jsonb,
      '{}'::jsonb
    )
  ) AS t(
    package_id,
    package_name,
    package_type,
    safe_description,
    full_description,
    marketing_tagline,
    price_usd,
    price_type,
    subscription_interval,
    regional_pricing,
    features,
    included_packages,
    version,
    content_version,
    min_app_version,
    max_app_version,
    content_changelog,
    is_active,
    is_featured,
    display_order,
    content_rating,
    preview_images,
    preview_video_url,
    localized_names,
    localized_descriptions
  )
)
INSERT INTO public.dlc_packages (
  package_id,
  package_name,
  package_type,
  safe_description,
  full_description,
  marketing_tagline,
  price_usd,
  price_type,
  subscription_interval,
  regional_pricing,
  features,
  included_packages,
  version,
  content_version,
  min_app_version,
  max_app_version,
  content_changelog,
  is_active,
  is_featured,
  display_order,
  content_rating,
  preview_images,
  preview_video_url,
  localized_names,
  localized_descriptions
)
SELECT
  package_id,
  package_name,
  package_type,
  safe_description,
  full_description,
  marketing_tagline,
  price_usd,
  price_type,
  subscription_interval,
  regional_pricing,
  -- If a row provides NULL features, keep existing DB features (don’t wipe).
  COALESCE(features, '[]'::jsonb),
  included_packages,
  version,
  content_version,
  min_app_version,
  max_app_version,
  content_changelog,
  is_active,
  is_featured,
  display_order,
  content_rating,
  preview_images,
  preview_video_url,
  localized_names,
  localized_descriptions
FROM catalog
WHERE public.is_nsfw_enabled()
ON CONFLICT (package_id) DO UPDATE SET
  package_name = EXCLUDED.package_name,
  package_type = EXCLUDED.package_type,
  safe_description = EXCLUDED.safe_description,
  full_description = EXCLUDED.full_description,
  marketing_tagline = EXCLUDED.marketing_tagline,
  price_usd = EXCLUDED.price_usd,
  price_type = EXCLUDED.price_type,
  subscription_interval = EXCLUDED.subscription_interval,
  regional_pricing = EXCLUDED.regional_pricing,
  features = COALESCE(EXCLUDED.features, public.dlc_packages.features),
  included_packages = EXCLUDED.included_packages,
  version = EXCLUDED.version,
  content_version = EXCLUDED.content_version,
  min_app_version = EXCLUDED.min_app_version,
  max_app_version = EXCLUDED.max_app_version,
  content_changelog = EXCLUDED.content_changelog,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  display_order = EXCLUDED.display_order,
  content_rating = EXCLUDED.content_rating,
  preview_images = EXCLUDED.preview_images,
  preview_video_url = EXCLUDED.preview_video_url,
  localized_names = EXCLUDED.localized_names,
  localized_descriptions = EXCLUDED.localized_descriptions,
  updated_at = now();

