-- Remote history placeholder migration.
--
-- This migration version exists in the remote `supabase_migrations` history table, but the
-- corresponding SQL file was not present in the repo, which caused `supabase db push` /
-- `supabase migration list` to report:
--   "Remote migration versions not found in local migrations directory."
--
-- Adding this no-op file keeps local migrations aligned with remote history.
--
-- Intentionally left blank.

