-- Add NSFW addon records for registry validation alignment
INSERT INTO premium_add_ons (
  addon_id,
  addon_name,
  addon_description,
  monthly_price,
  annual_price,
  lifetime_price,
  annual_discount_percentage,
  features,
  requires_tier,
  category,
  is_active,
  is_featured,
  is_popular,
  sort_order,
  icon_url
) VALUES
(
  'nsfw-scanner',
  'NSFW Scanner DLC',
  'Adult-only scanning mode with explicit-content detection controls and privacy-safe behavior. Disabled by default even when owned.',
  6.99,
  NULL,
  6.99,
  0,
  '["NSFW Scanner Mode","Explicit Content Detection"]'::jsonb,
  NULL,
  'nsfw',
  false,
  false,
  false,
  80,
  NULL
),
(
  'nsfw-advanced-detection',
  'Advanced NSFW Detection DLC',
  'Advanced NSFW detection modes: model selection, ensemble scoring, and opt-in detection history (no image content stored).',
  14.99,
  NULL,
  NULL,
  0,
  '["Model selection","Ensemble scoring","Opt-in detection history"]'::jsonb,
  NULL,
  'nsfw',
  false,
  false,
  false,
  81,
  NULL
)
ON CONFLICT (addon_id) DO UPDATE SET
  addon_name = EXCLUDED.addon_name,
  addon_description = EXCLUDED.addon_description,
  monthly_price = EXCLUDED.monthly_price,
  annual_price = EXCLUDED.annual_price,
  lifetime_price = EXCLUDED.lifetime_price,
  annual_discount_percentage = EXCLUDED.annual_discount_percentage,
  features = EXCLUDED.features,
  category = EXCLUDED.category,
  icon_url = EXCLUDED.icon_url,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
