// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isConfigured =
  typeof SUPABASE_URL === "string" &&
  SUPABASE_URL.length > 0 &&
  typeof SUPABASE_PUBLISHABLE_KEY === "string" &&
  SUPABASE_PUBLISHABLE_KEY.length > 0;

// Avoid hard-crashing the app when env is missing (tests/preview shells).
// Calls will still fail until real env is provided, but UI can render.
const FALLBACK_SUPABASE_URL = "https://example.supabase.co";
const FALLBACK_SUPABASE_ANON_KEY = "public-anon-key";

// Test localStorage availability for restricted contexts
const isLocalStorageAvailable = (): boolean => {
  if (typeof window === "undefined") return false;
  try {
    const testKey = "__supabase_test__";
    window.localStorage.setItem(testKey, "1");
    window.localStorage.removeItem(testKey);
    return true;
  } catch {
    return false;
  }
};

const safeStorage: Storage | undefined = isLocalStorageAvailable()
  ? window.localStorage
  : undefined;

export const supabase = createClient<Database>(
  isConfigured ? SUPABASE_URL : FALLBACK_SUPABASE_URL,
  isConfigured ? SUPABASE_PUBLISHABLE_KEY : FALLBACK_SUPABASE_ANON_KEY,
  {
    auth: {
      storage: safeStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  },
);
