// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = String(import.meta.env.VITE_SUPABASE_URL || "").trim();
const SUPABASE_PUBLISHABLE_KEY = String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "").trim();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isConfigured = SUPABASE_URL.length > 0 && SUPABASE_PUBLISHABLE_KEY.length > 0;
const isTestEnv = Boolean(import.meta.env.VITEST) || import.meta.env.MODE === "test";

const missingKeys = [
  ...(SUPABASE_URL ? [] : ["VITE_SUPABASE_URL"]),
  ...(SUPABASE_PUBLISHABLE_KEY ? [] : ["VITE_SUPABASE_PUBLISHABLE_KEY"]),
];

export const supabaseConfig = {
  isConfigured,
  missingKeys,
};

export const supabaseConfigError = isConfigured
  ? null
  : `Supabase is not configured. Missing: ${missingKeys.join(", ")}.`;

const supabaseNotConfiguredError = new Error(
  supabaseConfigError ||
    "Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.",
);

const createDisabledResult = <T,>(data: T | null = null) => ({
  data,
  error: supabaseNotConfiguredError,
});

const createDisabledBuilder = () => {
  const result = Promise.resolve(createDisabledResult());
  const builder = new Proxy(
    {},
    {
      get: (_target, prop) => {
        if (prop === "then") return result.then.bind(result);
        if (prop === "catch") return result.catch.bind(result);
        if (prop === "finally") return result.finally.bind(result);
        if (prop === Symbol.toStringTag) return "DisabledSupabaseBuilder";
        return () => builder;
      },
    },
  );
  return builder as unknown;
};

const createDisabledStorageBucket = () => {
  const result = Promise.resolve(createDisabledResult());
  const bucket = new Proxy(
    {},
    {
      get: (_target, prop) => {
        if (prop === "then") return result.then.bind(result);
        if (prop === "catch") return result.catch.bind(result);
        if (prop === "finally") return result.finally.bind(result);
        if (prop === Symbol.toStringTag) return "DisabledSupabaseStorageBucket";
        return async () => createDisabledResult();
      },
    },
  );
  return bucket as unknown;
};

const createDisabledChannel = () => {
  const channel = {
    on: () => channel,
    subscribe: () => channel,
    track: async () => createDisabledResult(),
    send: async () => createDisabledResult(),
    unsubscribe: async () => "ok",
  };
  return channel;
};

const createDisabledSupabaseClient = (): SupabaseClient<Database> => {
  return {
    auth: {
      onAuthStateChange: (callback: (event: string, session: unknown) => void) => {
        try {
          callback("SIGNED_OUT", null);
        } catch {
          // ignore
        }
        return {
          data: {
            subscription: {
              unsubscribe: () => undefined,
            },
          },
        };
      },
      getSession: async () => createDisabledResult({ session: null }),
      getUser: async () => createDisabledResult({ user: null }),
      signInWithPassword: async () => createDisabledResult({ session: null, user: null }),
      signUp: async () => createDisabledResult({ user: null }),
      signInWithOAuth: async () => createDisabledResult(),
      linkIdentity: async () => createDisabledResult(),
      signOut: async () => ({ error: supabaseNotConfiguredError }),
      resetPasswordForEmail: async () => createDisabledResult(),
      updateUser: async () => createDisabledResult({ user: null }),
      mfa: {
        listFactors: async () => createDisabledResult(),
        enroll: async () => createDisabledResult(),
        challengeAndVerify: async () => createDisabledResult(),
        unenroll: async () => createDisabledResult(),
        getAuthenticatorAssuranceLevel: async () => createDisabledResult(),
      },
    },
    from: () => createDisabledBuilder() as never,
    rpc: () => createDisabledBuilder() as never,
    functions: {
      invoke: async () => createDisabledResult(),
    },
    storage: {
      from: () => createDisabledStorageBucket() as never,
    },
    channel: () => createDisabledChannel() as never,
    removeChannel: async () => createDisabledResult(),
  } as unknown as SupabaseClient<Database>;
};

if (!isConfigured && !isTestEnv) {
  // eslint-disable-next-line no-console
  console.error(supabaseConfigError);
}

// Test localStorage availability for restricted contexts
const isLocalStorageAvailable = (): boolean => {
  if (typeof window === "undefined") return false;
  try {
    const testKey = "__supabase_test__";
    window.localStorage.setItem(testKey, "1");
    window.localStorage.removeItem(testKey);
    return true;
  } catch {
    return false;
  }
};

const safeStorage: Storage | undefined =
  isLocalStorageAvailable() ? window.localStorage : undefined;

export const supabase = isConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : createDisabledSupabaseClient();
