// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { readSupabaseRuntimeOverride } from "./runtimeOverride";

// Vite injects `import.meta.env`, but this module is also imported from Node-based scripts (tsx).
// Keep it safe in both environments.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const META_ENV: Record<string, unknown> =
  ((import.meta as any)?.env as Record<string, unknown>) || {};

// `process` is not defined in browsers by default; access via `globalThis` for a safe fallback.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const PROCESS_ENV: Record<string, string | undefined> =
  ((globalThis as any)?.process?.env as Record<string, string | undefined> | undefined) ?? {};

// Allow on-device/runtime overrides (useful for Android builds if keys are rotated).
// This is safe because the publishable key is intended to be public.
const RUNTIME_OVERRIDE = readSupabaseRuntimeOverride();

const SUPABASE_URL = String(
  (RUNTIME_OVERRIDE.url as string | undefined) ||
    (META_ENV.VITE_SUPABASE_URL as string | undefined) ||
    PROCESS_ENV.VITE_SUPABASE_URL ||
    "",
).trim();
const SUPABASE_PUBLISHABLE_KEY = String(
  (RUNTIME_OVERRIDE.publishableKey as string | undefined) ||
    (META_ENV.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ||
    PROCESS_ENV.VITE_SUPABASE_PUBLISHABLE_KEY ||
    "",
).trim();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isConfigured = SUPABASE_URL.length > 0 && SUPABASE_PUBLISHABLE_KEY.length > 0;
const isTestEnv = Boolean(META_ENV.VITEST) || META_ENV.MODE === "test";

const missingKeys = [
  ...(SUPABASE_URL ? [] : ["VITE_SUPABASE_URL"]),
  ...(SUPABASE_PUBLISHABLE_KEY ? [] : ["VITE_SUPABASE_PUBLISHABLE_KEY"]),
];

export const supabaseConfig = {
  isConfigured,
  missingKeys,
};

// Public values (safe to ship). Helpful for on-device diagnostics UI.
export const supabasePublicConfig = {
  url: SUPABASE_URL,
  publishableKey: SUPABASE_PUBLISHABLE_KEY,
};

export const supabaseConfigError = isConfigured
  ? null
  : `Supabase is not configured. Missing: ${missingKeys.join(", ")}.`;

const supabaseNotConfiguredError = new Error(
  supabaseConfigError ||
    "Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.",
);

const createDisabledResult = <T>(data: T | null = null) => ({
  data,
  error: supabaseNotConfiguredError,
});

const createDisabledBuilder = () => {
  const result = Promise.resolve(createDisabledResult());
  const builder = new Proxy(
    {},
    {
      get: (_target, prop) => {
        if (prop === "then") return result.then.bind(result);
        if (prop === "catch") return result.catch.bind(result);
        if (prop === "finally") return result.finally.bind(result);
        if (prop === Symbol.toStringTag) return "DisabledSupabaseBuilder";
        return () => builder;
      },
    },
  );
  return builder as unknown;
};

const createDisabledStorageBucket = () => {
  const result = Promise.resolve(createDisabledResult());
  const bucket = new Proxy(
    {},
    {
      get: (_target, prop) => {
        if (prop === "then") return result.then.bind(result);
        if (prop === "catch") return result.catch.bind(result);
        if (prop === "finally") return result.finally.bind(result);
        if (prop === Symbol.toStringTag) return "DisabledSupabaseStorageBucket";
        return async () => createDisabledResult();
      },
    },
  );
  return bucket as unknown;
};

const createDisabledChannel = () => {
  const channel = {
    on: () => channel,
    subscribe: () => channel,
    track: async () => createDisabledResult(),
    send: async () => createDisabledResult(),
    unsubscribe: async () => "ok",
  };
  return channel;
};

const createDisabledSupabaseClient = (): SupabaseClient<Database> => {
  return {
    auth: {
      onAuthStateChange: (callback: (event: string, session: unknown) => void) => {
        try {
          callback("SIGNED_OUT", null);
        } catch {
          // ignore
        }
        return {
          data: {
            subscription: {
              unsubscribe: () => undefined,
            },
          },
        };
      },
      getSession: async () => createDisabledResult({ session: null }),
      getUser: async () => createDisabledResult({ user: null }),
      signInWithPassword: async () => createDisabledResult({ session: null, user: null }),
      signUp: async () => createDisabledResult({ user: null }),
      signInWithOAuth: async () => createDisabledResult(),
      linkIdentity: async () => createDisabledResult(),
      signOut: async () => ({ error: supabaseNotConfiguredError }),
      resetPasswordForEmail: async () => createDisabledResult(),
      updateUser: async () => createDisabledResult({ user: null }),
      mfa: {
        listFactors: async () => createDisabledResult(),
        enroll: async () => createDisabledResult(),
        challengeAndVerify: async () => createDisabledResult(),
        unenroll: async () => createDisabledResult(),
        getAuthenticatorAssuranceLevel: async () => createDisabledResult(),
      },
    },
    from: () => createDisabledBuilder() as never,
    rpc: () => createDisabledBuilder() as never,
    functions: {
      invoke: async () => createDisabledResult(),
    },
    storage: {
      from: () => createDisabledStorageBucket() as never,
    },
    channel: () => createDisabledChannel() as never,
    removeChannel: async () => createDisabledResult(),
  } as unknown as SupabaseClient<Database>;
};

if (!isConfigured && !isTestEnv) {
  // eslint-disable-next-line no-console
  console.error(supabaseConfigError);
}

// Test localStorage availability for restricted contexts
const isLocalStorageAvailable = (): boolean => {
  if (typeof window === "undefined") return false;
  try {
    const testKey = "__supabase_test__";
    window.localStorage.setItem(testKey, "1");
    window.localStorage.removeItem(testKey);
    return true;
  } catch {
    return false;
  }
};

const safeStorage: Storage | undefined = isLocalStorageAvailable()
  ? window.localStorage
  : undefined;

export const supabase = isConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : createDisabledSupabaseClient();
