import {
  Activity,
  AlertTriangle,
  BarChart3,
  BookOpen,
  Brain,
  ClipboardList,
  Camera,
  Calendar,
  CalendarHeart,
  Crown,
  Database,
  Dumbbell,
  Download,
  Eye,
  FileText,
  Flame,
  GraduationCap,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  ImageIcon,
  Key,
  Layers,
  ListChecks,
  Lock,
  MapPin,
  MessageSquare,
  Package,
  Plus,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  Sparkles,
  Stethoscope,
  Target,
  TrendingUp,
  User,
  UserCheck,
  Users,
  Video,
  Watch,
} from "lucide-react";
import { BUILD_ALLOW_ADULT_BUNDLE } from "@/lib/buildFlags";

export type { NavCategory, NavItem } from "./navTypes";
import type { NavCategory } from "./navTypes";

export const NAV_CATEGORIES: NavCategory[] = [
  {
    label: "Main",
    icon: Home,
    items: [
      { id: "home", label: "Home", icon: Home, kind: "tab" },
      { id: "scanner", label: "Scan", icon: Activity, kind: "tab" },
      { id: "progress", label: "Progress", icon: TrendingUp, kind: "tab" },
      { id: "learn", label: "Learn", icon: BookOpen, kind: "tab" },
      { id: "community", label: "Community", icon: Users, kind: "tab" },
      { id: "profile", label: "Profile", icon: User, kind: "tab" },
    ],
  },
  {
    label: "Partner & Intimacy",
    icon: HeartHandshake,
    items: [
      { id: "partner-sync", label: "Partner Sync", icon: Users, kind: "tab" },
      { id: "date-night-planner", label: "Date Night Planner", icon: CalendarHeart, kind: "tab" },
      { id: "date-night-templates", label: "Date Templates", icon: ListChecks, kind: "tab" },
      { id: "date-night-history", label: "Date History", icon: Calendar, kind: "tab" },
      { id: "positions", label: "Positions Gallery", icon: Sparkles, kind: "tab" },
    ],
  },
  {
    label: "Progress & Photos",
    icon: Camera,
    items: [
      { id: "diary", label: "Health Diary", icon: BookOpen, kind: "tab" },
      { id: "pumping", label: "Pumping", icon: TrendingUp, kind: "tab" },
      { id: "routines", label: "Routines", icon: Calendar, kind: "tab" },
      { id: "pe-progress", label: "PE Progress Photos", icon: Camera, kind: "tab" },
      { id: "video-capture", label: "Video Capture", icon: Video, kind: "tab" },
      { id: "photo-editor", label: "Photo Editor", icon: ImageIcon, kind: "tab" },
      { id: "advanced-reporting", label: "Reports", icon: FileText, kind: "tab" },
      { id: "enhanced-diary", label: "Enhanced Diary", icon: BookOpen, kind: "tab", premiumOnly: true },
      { id: "advanced-routines", label: "Advanced Routines", icon: Sparkles, kind: "tab", premiumOnly: true },
    ],
  },
  {
    label: "Health & Monitoring",
    icon: Heart,
    items: [
      { id: "health-dashboard", label: "Health Dashboard", icon: BarChart3, kind: "tab" },
      { id: "health-monitoring", label: "Health Monitor", icon: Heart, kind: "tab" },
      { id: "prostate-testicular", label: "Prostate/Testicular", icon: Stethoscope, kind: "tab" },
      { id: "sexual-wellness", label: "Sexual Wellness", icon: HeartPulse, kind: "tab" },
      { id: "pelvic-floor", label: "Pelvic Floor", icon: Target, kind: "tab" },
      { id: "habit-tracker", label: "Habit Tracker", icon: Target, kind: "tab" },
      { id: "ai-insights", label: "AI Insights", icon: Brain, kind: "tab" },
      { id: "predictive-modeling", label: "Predictions", icon: Sparkles, kind: "tab" },
    ],
  },
  {
    label: "Learning & Guidance",
    icon: GraduationCap,
    items: [
      {
        id: "measurements-vs-average-men",
        label: "Size Comparison",
        icon: Users,
        kind: "route",
        to: "/measurements-vs-average-men",
      },
      {
        id: "growers-vs-showers",
        label: "Growers vs Showers",
        icon: TrendingUp,
        kind: "route",
        to: "/growers-vs-showers",
        superAdminOnly: true,
      },
      { id: "guide", label: "PE Guide", icon: Dumbbell, kind: "tab" },
      { id: "sexual-health-education", label: "Sexual Health", icon: GraduationCap, kind: "tab" },
      { id: "education", label: "Health Info", icon: AlertTriangle, kind: "tab" },
      { id: "interactive-learning", label: "Courses", icon: GraduationCap, kind: "tab" },
      { id: "video-library", label: "Video Library", icon: Video, kind: "tab" },
      { id: "learn", label: "Learning Library", icon: BookOpen, kind: "tab" },
      { id: "ai-chat", label: "AI Chat", icon: Brain, kind: "tab" },
      { id: "ai-enhancement", label: "AI Enhancements", icon: Brain, kind: "tab" },
      { id: "expert-consultations", label: "Expert Consultations", icon: UserCheck, kind: "tab" },
      { id: "doctors", label: "Find Doctors", icon: MapPin, kind: "tab" },
      { id: "questionnaire", label: "Assessment", icon: ClipboardList, kind: "tab" },
      { id: "emergency", label: "Emergency", icon: AlertTriangle, kind: "tab" },
    ],
  },
  {
    label: "Community & Support",
    icon: Users,
    items: [
      { id: "community-forum", label: "Forum", icon: MessageSquare, kind: "tab" },
      { id: "progress-sharing", label: "Progress Sharing", icon: Share2, kind: "tab" },
      { id: "in-app-messaging", label: "Messages", icon: MessageSquare, kind: "tab" },
      { id: "live-support", label: "Support", icon: Headphones, kind: "tab" },
    ],
  },
  {
    label: "Marketplace & Plans",
    icon: ShoppingBag,
    items: [
      { id: "subscription-tiers", label: "Plans", icon: Crown, kind: "tab" },
      { id: "dlc-system", label: "DLC Store", icon: Package, kind: "tab" },
      { id: "premium-marketplace", label: "Marketplace", icon: ShoppingBag, kind: "tab" },
      { id: "premium-addons", label: "Add-Ons", icon: Plus, kind: "tab" },
      { id: "marketplace", label: "All Products", icon: ShoppingBag, kind: "tab" },
    ],
  },
  {
    label: "Account & Settings",
    icon: Settings,
    items: [
      { id: "settings", label: "Settings", icon: Settings, kind: "tab" },
      { id: "security-privacy", label: "Security & Privacy", icon: Shield, kind: "tab" },
      { id: "privacy", label: "Privacy Settings", icon: Lock, kind: "tab" },
      { id: "activity", label: "Activity Log", icon: Activity, kind: "tab" },
      { id: "health-integrations", label: "Health Apps", icon: Activity, kind: "tab" },
      { id: "api-webhooks", label: "API", icon: Key, kind: "tab" },
      { id: "export-import", label: "Export/Import", icon: Download, kind: "tab" },
      { id: "mobile-wearable", label: "Mobile/Wearable", icon: Watch, kind: "tab" },
      { id: "provider-portal", label: "Provider Dashboard", icon: Stethoscope, kind: "tab" },
      { id: "3dviewer", label: "3D Viewer", icon: Layers, kind: "tab" },
    ],
  },
  ...(BUILD_ALLOW_ADULT_BUNDLE
    ? ([
        {
          label: "NSFW Content",
          icon: Flame,
          items: [
            {
              id: "nsfw-cock-worshiping",
              label: "Intimate Education",
              icon: BookOpen,
              kind: "tab",
              nsfwOnly: true,
            },
            { id: "nsfw-videos", label: "NSFW Videos", icon: Video, kind: "tab", nsfwOnly: true },
            {
              id: "nsfw-forum",
              label: "NSFW Forum",
              icon: MessageSquare,
              kind: "tab",
              nsfwOnly: true,
            },
            {
              id: "nsfw-wellness-analytics",
              label: "NSFW Analytics",
              icon: BarChart3,
              kind: "tab",
              nsfwOnly: true,
            },
            { id: "nsfw-advanced", label: "NSFW Advanced", icon: Eye, kind: "tab", nsfwOnly: true },
          ],
        },
      ] as NavCategory[])
    : []),
];

const ADMIN_NAV_ITEMS: NavCategory["items"] = [
  {
    id: "admin",
    label: "Admin Dashboard",
    icon: Shield,
    adminOnly: true,
    kind: "route",
    to: "/admin",
  },
  {
    id: "admin-dlc",
    label: "DLC Management",
    icon: Package,
    adminOnly: true,
    kind: "route",
    to: "/admin/dlc",
  },
  ...(BUILD_ALLOW_ADULT_BUNDLE
    ? ([
        {
          id: "admin-nsfw",
          label: "NSFW Content",
          icon: Flame,
          adminOnly: true,
          kind: "route",
          to: "/admin/nsfw",
        },
      ] as NavCategory["items"])
    : []),
  {
    id: "admin-users",
    label: "User Management",
    icon: Users,
    adminOnly: true,
    kind: "route",
    to: "/admin/users",
  },
  {
    id: "admin-content",
    label: "Content Moderation",
    icon: FileText,
    adminOnly: true,
    kind: "route",
    to: "/admin/content",
  },
  {
    id: "admin-analytics",
    label: "Analytics Dashboard",
    icon: BarChart3,
    adminOnly: true,
    kind: "route",
    to: "/admin/analytics",
  },
  {
    id: "admin-settings",
    label: "System Settings",
    icon: Settings,
    adminOnly: true,
    kind: "route",
    to: "/admin/settings",
  },
  {
    id: "admin-database",
    label: "Database",
    icon: Database,
    adminOnly: true,
    kind: "route",
    to: "/admin/database",
  },
];

export const ADMIN_NAV_CATEGORY: NavCategory = {
  label: "Admin Panel",
  icon: Shield,
  adminOnly: true,
  items: ADMIN_NAV_ITEMS,
};

// Note: the header navigation has its own layout/visibility logic. This catalog is used for
// global navigation surfaces (dropdown, command palette), so it should remain stable and
// tab-ID-driven.
